version: "3.9"
services:
  client:
    build: ./client/
    depends_on: 
      - db
    ports:
      - ${CLIENT_PORT:-3000}:3000
    networks:
      - internal
    environment:
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      CLIENT_PASSWORD: ${CLIENT_PASSWORD}
      MYSQL_HOST: db 
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bluesky-app} 

  db:
    build: ./db/
    networks:
      - internal
    volumes: 
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bluesky-app} 

  service:
    build: ./service/
    depends_on: 
      - db
    networks:
      - internal
    environment:
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      CLIENT_PASSWORD: ${CLIENT_PASSWORD}
      MYSQL_HOST: db 
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bluesky-app} 

networks:
  internal:
    driver: bridge

volumes:
  mysql-data:
