CREATE TABLE IF NOT EXISTS POSTS (
    POST_ID INT NOT NULL AUTO_INCREMENT,
    TEXT VARCHAR(300) NOT NULL,
    POST_DATE DATETIME NOT NULL,
    SENT BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (POST_ID)
);
